# coding: utf-8

"""
    Timmi Timesheet API

    Welcome on the documentation for the Timmi Timesheet API. 

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: https://www.lucca.fr
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lucca_timmi_timesheet_python_sdk import schemas  # noqa: F401


class WorkflowSubmitTimesheetRequestTimesheetsItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "startsAt",
            "ownerId",
            "endsAt",
        }
        
        class properties:
            startsAt = schemas.DateSchema
            endsAt = schemas.DateSchema
            
            
            class ownerId(
                schemas.IntSchema
            ):
            
            
                class MetaOapg:
                    inclusive_minimum = 1
            
            
            class transfers(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    min_items = 0
                    
                    @staticmethod
                    def items() -> typing.Type['Transfer']:
                        return Transfer
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['Transfer'], typing.List['Transfer']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'transfers':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Transfer':
                    return super().__getitem__(i)
            __annotations__ = {
                "startsAt": startsAt,
                "endsAt": endsAt,
                "ownerId": ownerId,
                "transfers": transfers,
            }
    
    startsAt: MetaOapg.properties.startsAt
    ownerId: MetaOapg.properties.ownerId
    endsAt: MetaOapg.properties.endsAt
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["startsAt"]) -> MetaOapg.properties.startsAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["endsAt"]) -> MetaOapg.properties.endsAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ownerId"]) -> MetaOapg.properties.ownerId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transfers"]) -> MetaOapg.properties.transfers: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["startsAt", "endsAt", "ownerId", "transfers", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["startsAt"]) -> MetaOapg.properties.startsAt: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["endsAt"]) -> MetaOapg.properties.endsAt: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ownerId"]) -> MetaOapg.properties.ownerId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transfers"]) -> typing.Union[MetaOapg.properties.transfers, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["startsAt", "endsAt", "ownerId", "transfers", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        startsAt: typing.Union[MetaOapg.properties.startsAt, str, date, ],
        ownerId: typing.Union[MetaOapg.properties.ownerId, decimal.Decimal, int, ],
        endsAt: typing.Union[MetaOapg.properties.endsAt, str, date, ],
        transfers: typing.Union[MetaOapg.properties.transfers, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'WorkflowSubmitTimesheetRequestTimesheetsItem':
        return super().__new__(
            cls,
            *args,
            startsAt=startsAt,
            ownerId=ownerId,
            endsAt=endsAt,
            transfers=transfers,
            _configuration=_configuration,
            **kwargs,
        )

from lucca_timmi_timesheet_python_sdk.model.transfer import Transfer
