# coding: utf-8

"""
    Timmi Timesheet API

    Welcome on the documentation for the Timmi Timesheet API. 

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: https://www.lucca.fr
"""

from lucca_timmi_timesheet_python_sdk.paths.timmi_timesheet_api_reports.post import CreateBasedOnTemplate
from lucca_timmi_timesheet_python_sdk.paths.timmi_timesheet_api_reports_report_id_download_csv.get import DownloadCsvReport
from lucca_timmi_timesheet_python_sdk.paths.timmi_timesheet_api_reports_report_id_download_excel.get import DownloadExcelReport
from lucca_timmi_timesheet_python_sdk.apis.tags.reports_api_raw import ReportsApiRaw


class ReportsApi(
    CreateBasedOnTemplate,
    DownloadCsvReport,
    DownloadExcelReport,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ReportsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ReportsApiRaw(api_client)
