# coding: utf-8

"""
    Timmi Timesheet API

    Welcome on the documentation for the Timmi Timesheet API. 

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: https://www.lucca.fr
"""

from lucca_timmi_timesheet_python_sdk.paths.api_v3_timeentries.post import CreateMultiple
from lucca_timmi_timesheet_python_sdk.paths.api_v3_timeentries.delete import DeleteMultiple
from lucca_timmi_timesheet_python_sdk.paths.api_v3_timeentries_time_entry_id.get import GetById
from lucca_timmi_timesheet_python_sdk.paths.api_v3_timeentries.get import ListTimeEntries
from lucca_timmi_timesheet_python_sdk.paths.api_v3_timeentries_time_entry_id.delete import RemoveById
from lucca_timmi_timesheet_python_sdk.paths.api_v3_timeentries_time_entry_id.put import UpdateById
from lucca_timmi_timesheet_python_sdk.paths.api_v3_timeentries.put import UpdateMultiple
from lucca_timmi_timesheet_python_sdk.apis.tags.time_entries_api_raw import TimeEntriesApiRaw


class TimeEntriesApi(
    CreateMultiple,
    DeleteMultiple,
    GetById,
    ListTimeEntries,
    RemoveById,
    UpdateById,
    UpdateMultiple,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TimeEntriesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TimeEntriesApiRaw(api_client)
