# coding: utf-8

"""
    Timmi Timesheet API

    Welcome on the documentation for the Timmi Timesheet API. 

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: https://www.lucca.fr
"""

from lucca_timmi_timesheet_python_sdk.paths.api_v3_timeentries.post import CreateMultipleRaw
from lucca_timmi_timesheet_python_sdk.paths.api_v3_timeentries.delete import DeleteMultipleRaw
from lucca_timmi_timesheet_python_sdk.paths.api_v3_timeentries_time_entry_id.get import GetByIdRaw
from lucca_timmi_timesheet_python_sdk.paths.api_v3_timeentries.get import ListTimeEntriesRaw
from lucca_timmi_timesheet_python_sdk.paths.api_v3_timeentries_time_entry_id.delete import RemoveByIdRaw
from lucca_timmi_timesheet_python_sdk.paths.api_v3_timeentries_time_entry_id.put import UpdateByIdRaw
from lucca_timmi_timesheet_python_sdk.paths.api_v3_timeentries.put import UpdateMultipleRaw


class TimeEntriesApiRaw(
    CreateMultipleRaw,
    DeleteMultipleRaw,
    GetByIdRaw,
    ListTimeEntriesRaw,
    RemoveByIdRaw,
    UpdateByIdRaw,
    UpdateMultipleRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
