# coding: utf-8

"""
    Timmi Timesheet API

    Welcome on the documentation for the Timmi Timesheet API. 

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: https://www.lucca.fr
"""

from lucca_timmi_timesheet_python_sdk.paths.api_v3_timmitimesheets.get import List
from lucca_timmi_timesheet_python_sdk.paths.api_v3_timmitimesheets_remindable.get import ListDue
from lucca_timmi_timesheet_python_sdk.apis.tags.timesheets_api_raw import TimesheetsApiRaw


class TimesheetsApi(
    List,
    ListDue,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TimesheetsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TimesheetsApiRaw(api_client)
