# coding: utf-8

"""
    Timmi Timesheet API

    Welcome on the documentation for the Timmi Timesheet API. 

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: https://www.lucca.fr
"""

from lucca_timmi_timesheet_python_sdk.paths.timmi_services_workflow_approve.post import ApproveTimesheetsById
from lucca_timmi_timesheet_python_sdk.paths.timmi_services_workflow_cancel.post import CancelTimesheetById
from lucca_timmi_timesheet_python_sdk.paths.timmi_services_workflow_deny.post import DenyTimesheetById
from lucca_timmi_timesheet_python_sdk.paths.timmi_services_workflow_invalidate.post import InvalidateTimesheetById
from lucca_timmi_timesheet_python_sdk.paths.timmi_services_workflow_remind.post import SendReminderEmail
from lucca_timmi_timesheet_python_sdk.paths.timmi_services_workflow_submit.post import SubmitTimesheet
from lucca_timmi_timesheet_python_sdk.apis.tags.workflow_api_raw import WorkflowApiRaw


class WorkflowApi(
    ApproveTimesheetsById,
    CancelTimesheetById,
    DenyTimesheetById,
    InvalidateTimesheetById,
    SendReminderEmail,
    SubmitTimesheet,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WorkflowApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WorkflowApiRaw(api_client)
