# coding: utf-8

"""
    Timmi Timesheet API

    Welcome on the documentation for the Timmi Timesheet API. 

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: https://www.lucca.fr
"""

from lucca_timmi_timesheet_python_sdk.paths.timmi_services_workflow_approve.post import ApproveTimesheetsByIdRaw
from lucca_timmi_timesheet_python_sdk.paths.timmi_services_workflow_cancel.post import CancelTimesheetByIdRaw
from lucca_timmi_timesheet_python_sdk.paths.timmi_services_workflow_deny.post import DenyTimesheetByIdRaw
from lucca_timmi_timesheet_python_sdk.paths.timmi_services_workflow_invalidate.post import InvalidateTimesheetByIdRaw
from lucca_timmi_timesheet_python_sdk.paths.timmi_services_workflow_remind.post import SendReminderEmailRaw
from lucca_timmi_timesheet_python_sdk.paths.timmi_services_workflow_submit.post import SubmitTimesheetRaw


class WorkflowApiRaw(
    ApproveTimesheetsByIdRaw,
    CancelTimesheetByIdRaw,
    DenyTimesheetByIdRaw,
    InvalidateTimesheetByIdRaw,
    SendReminderEmailRaw,
    SubmitTimesheetRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
